import Link from "next/link";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default async function About() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts",
    { 
      next: {
        revalidate: 120,
    }}
  );
  const posts = await response.json();

  console.log(posts);

  const postJSON = posts.map((post) => {
    return (
      <>
        <Link href={`/posts/${post.id}`}>
          <div style={{border: "1px solid black", padding: "10px", margin: "10px", borderRadius: "7px"}}>
            <div style={{fontSize:"1.5rem"}}>{post.title}</div>
            <p>{post.body}</p>
          </div>
        </Link>
      </>

    )
  })

  return (
    <>
      <div>
        <div style={{fontSize:"3rem", paddingLeft:"10px", borderRadius:"7px"}}>About page</div>
          <div>{postJSON}</div>
      </div>
    </>
  )
}
