import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "test",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 style={{alignItems:"center", justifyContent:"center", textAlign:"center", fontSize:"3rem"}}>My Website</h1>
          <nav style={{ display: "flex", gap: "10px", alignItems: "center", justifyContent: "center", fontSize: "1.5rem" }}>
            <Link href="/" style={{border:"1", backgroundColor:"black", color:"white",padding:"8px", borderRadius:"7px"}}>Home</Link>
            <Link href="/about" style={{border:"1", backgroundColor:"black", color:"white",padding:"8px", borderRadius:"7px"}}>About</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
