import styles from "./globals.module.css"; 
import Link from "next/link";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function Home() {

  return (
    <div style={{textAlign: "center", fontSize:"60px", paddingTop:"160px"}}>
      <code>Welcome to My Next.js App!</code>
    </div>
  );
}