export async function generateMetadata({ params }) {
    return {
      title: `Post ${params.postId}`,
      description: "Generated by create next app",
    };
  }

export default async function Post({params}) {
    const PostId = params.postId;

    await new Promise((resolve) => {
        setTimeout(resolve, 3000);
    });

    const response = await fetch(`https://jsonplaceholder.typicode.com/posts/${PostId}`, 
        {
            next: {
                revalidate: 120,
        }}
    )

    const post = await response.json();

    return (
        <div style={{border: "1px solid black", padding: "10px", margin: "10px", borderRadius: "7px", alignItems:"center", justifyContent:"center"}}>
            <h1 style={{fontSize:"2rem", fontStyle:"bold"}}>{post.title}</h1>
            <p>{post.body}</p>
        </div>
    )
}    